export type MenuItemData = {
  id: string
  category: string
  nameKo: string
  nameEn: string
  nameJa: string
  nameZh: string
  nameEs: string
  nameTh: string
  nameVi: string
  descKo: string
  descEn: string
  descJa: string
  descZh: string
  descEs: string
  descTh: string
  descVi: string
  priceKRW: number
  image?: string
}

export const menuData: MenuItemData[] = [
  {
    id: "macallan25",
    category: "spirits",
    nameKo: "맥깔란 25년",
    nameEn: "Macallan 25 Years",
    nameJa: "マッカラン 25年",
    nameZh: "麦卡伦 25年",
    nameEs: "Macallan 25 años",
    nameTh: "แม็คแคลลัน 25 ปี",
    nameVi: "Macallan 25 năm",
    descKo: "스코틀랜드 싱글 몰트 위스키의 최고 걸작",
    descEn: "A masterpiece of Scottish single malt whisky",
    descJa: "スコットランド シングルモルト ウイスキーの傑作",
    descZh: "苏格兰单一麦芽威士忌的杰作",
    descEs: "Una obra maestra del whisky de malta única escocés",
    descTh: "ผลงานชิ้นเอก ของ Single Malt Whisky สกอตแลนด์",
    descVi: "Một kiệt tác của Single Malt Whisky Scotland",
    priceKRW: 450000,
    image: "/macallan-25-whisky.jpg",
  },
  {
    id: "glenfiddich",
    category: "spirits",
    nameKo: "글렌피디 12년",
    nameEn: "Glenfiddich 12 Years",
    nameJa: "グレンフィディック 12年",
    nameZh: "格兰菲迪 12年",
    nameEs: "Glenfiddich 12 años",
    nameTh: "เกลนฟิดิช 12 ปี",
    nameVi: "Glenfiddich 12 năm",
    descKo: "부드럽고 매력적인 싱글 몰트",
    descEn: "A smooth and appealing single malt",
    descJa: "スムーズで魅力的なシングルモルト",
    descZh: "光滑诱人的单一麦芽威士忌",
    descEs: "Un single malt suave y atractivo",
    descTh: "Single Malt ที่นุ่มและน่าดึงดูด",
    descVi: "Single Malt mịn và hấp dẫn",
    priceKRW: 120000,
    image: "/glenfiddich-whisky.jpg",
  },
  {
    id: "johnnyWalker",
    category: "spirits",
    nameKo: "조니워커 블루라벨",
    nameEn: "Johnnie Walker Blue Label",
    nameJa: "ジョニーウォーカー ブルーラベル",
    nameZh: "尊尼获加 蓝牌",
    nameEs: "Johnnie Walker Blue Label",
    nameTh: "จอห์นนี่ วอล์คเกอร์ บลูเลเบล",
    nameVi: "Johnnie Walker Blue Label",
    descKo: "프리미엄 블렌디드 위스키의 상징",
    descEn: "The epitome of premium blended whisky",
    descJa: "プレミアムブレンデッドウイスキーの象徴",
    descZh: "高级混合威士忌的象征",
    descEs: "El epítome del whisky mezclado premium",
    descTh: "สัญลักษณ์ของ Blended Whisky ระดับพรีเมียม",
    descVi: "Biểu tượng của Blended Whisky hạng sang",
    priceKRW: 180000,
    image: "/johnnie-walker-blue-label.jpg",
  },
  {
    id: "heineken",
    category: "beers",
    nameKo: "하이네켄",
    nameEn: "Heineken",
    nameJa: "ハイネケン",
    nameZh: "喜力",
    nameEs: "Heineken",
    nameTh: "ไฮเนเกน",
    nameVi: "Heineken",
    descKo: "네덜란드 프리미엄 필스너",
    descEn: "Dutch premium pilsner",
    descJa: "オランダのプレミアムピルスナー",
    descZh: "荷兰优质皮尔森啤酒",
    descEs: "Cerveza pilsner premium holandesa",
    descTh: "เบียร์ Pilsner ระดับพรีเมียมจากเนเธอร์แลนด์",
    descVi: "Bia Pilsner cao cấp Hà Lan",
    priceKRW: 18000,
    image: "/heineken-beer.jpg",
  },
  {
    id: "chimayBlue",
    category: "beers",
    nameKo: "시메이 블루",
    nameEn: "Chimay Blue",
    nameJa: "シメイ ブルー",
    nameZh: "希美艾蓝",
    nameEs: "Chimay Azul",
    nameTh: "ชิเมย์ บลู",
    nameVi: "Chimay Xanh",
    descKo: "벨기에 트라피스트 수도사 맥주",
    descEn: "Belgian Trappist monk beer",
    descJa: "ベルギー トラピスト修道士ビール",
    descZh: "比利时修道士啤酒",
    descEs: "Cerveza de monje trapense belga",
    descTh: "เบียร์ Trappist Monk ของเบลเยียม",
    descVi: "Bia Monk Trappist Bỉ",
    priceKRW: 35000,
    image: "/chimay-blue-beer.jpg",
  },
  {
    id: "domPerignon",
    category: "wines",
    nameKo: "돔 페리뇽",
    nameEn: "Dom Pérignon",
    nameJa: "ドン・ペリニヨン",
    nameZh: "唐培里侬",
    nameEs: "Dom Pérignon",
    nameTh: "ดอม เปริญญง",
    nameVi: "Dom Pérignon",
    descKo: "프랑스 샴페인의 전설",
    descEn: "Legend of French champagne",
    descJa: "フランスシャンパンの伝説",
    descZh: "法国香槟的传奇",
    descEs: "La leyenda del champagne francés",
    descTh: "ตำนานของแชมเปญฝรั่งเศส",
    descVi: "Huyền thoại Champagne Pháp",
    priceKRW: 250000,
    image: "/dom-perignon-champagne.jpg",
  },
  {
    id: "petrusMerlot",
    category: "wines",
    nameKo: "페트뤼스 메를롯",
    nameEn: "Petrus Merlot",
    nameJa: "ペトリュス メルロー",
    nameZh: "柏图斯梅洛",
    nameEs: "Petrus Merlot",
    nameTh: "เพทรัส เมอร์โลต์",
    nameVi: "Petrus Merlot",
    descKo: "프랑스 보르도 와인의 최고봉",
    descEn: "The pinnacle of French Bordeaux wine",
    descJa: "フランス ボルドーワインの最高峰",
    descZh: "法国波尔多葡萄酒的顶峰",
    descEs: "La cumbre del vino tinto de Burdeos francés",
    descTh: "จุดสูงสุดของ Bordeaux Wine ฝรั่งเศส",
    descVi: "Đỉnh cao của rượu vang Bordeaux Pháp",
    priceKRW: 350000,
    image: "/petrus-wine.jpg",
  },
  {
    id: "mojito",
    category: "cocktails",
    nameKo: "모히또",
    nameEn: "Mojito",
    nameJa: "モヒート",
    nameZh: "莫吉托",
    nameEs: "Mojito",
    nameTh: "โมฮิโต้",
    nameVi: "Mojito",
    descKo: "상큼한 민트와 라임의 시원한 칵테일",
    descEn: "A refreshing cocktail of mint and lime",
    descJa: "ミントとライムのさっぱりしたカクテル",
    descZh: "薄荷和青柠的清爽鸡尾酒",
    descEs: "Un cóctel refrescante de menta y lima",
    descTh: "ค็อกเทลสดชื่นของมิ้นต์และมะนาว",
    descVi: "Cocktail tươi mới của bạc hà và chanh",
    priceKRW: 22000,
    image: "/mojito-cocktail.jpg",
  },
  {
    id: "margarita",
    category: "cocktails",
    nameKo: "마가리타",
    nameEn: "Margarita",
    nameJa: "マルガリータ",
    nameZh: "玛格丽塔",
    nameEs: "Margarita",
    nameTh: "มาร์การิต้า",
    nameVi: "Margarita",
    descKo: "시원하고 신맛이 매력적인 칵테일",
    descEn: "A cool and tangy cocktail",
    descJa: "クールでタンギーなカクテル",
    descZh: "清爽而酸的鸡尾酒",
    descEs: "Un cóctel fresco y ácido",
    descTh: "ค็อกเทลเย็นและเปรี้ยว",
    descVi: "Cocktail mát mẻ và chua",
    priceKRW: 25000,
    image: "/margarita-cocktail.jpg",
  },
  {
    id: "cosmopolitan",
    category: "cocktails",
    nameKo: "코스모폴리탄",
    nameEn: "Cosmopolitan",
    nameJa: "コスモポリタン",
    nameZh: "大都会",
    nameEs: "Cosmopolitan",
    nameTh: "คอ Côโมพลิทัน",
    nameVi: "Cosmopolitan",
    descKo: "우아하고 세련된 칵테일",
    descEn: "An elegant and sophisticated cocktail",
    descJa: "エレガントで洗練されたカクテル",
    descZh: "优雅而精致的鸡尾酒",
    descEs: "Un cóctel elegante y sofisticado",
    descTh: "ค็อกเทลที่หรูหราและซับซ้อน",
    descVi: "Cocktail thanh lịch và tinh tế",
    priceKRW: 28000,
    image: "/cosmopolitan-cocktail.jpg",
  },
  {
    id: "baileys",
    category: "liqueurs",
    nameKo: "베일리스",
    nameEn: "Baileys",
    nameJa: "ベイリーズ",
    nameZh: "百利甜",
    nameEs: "Baileys",
    nameTh: "เบลี่ย์",
    nameVi: "Baileys",
    descKo: "크리미하고 부드러운 리큐르",
    descEn: "A creamy and smooth liqueur",
    descJa: "クリーミーでなめらかなリキュール",
    descZh: "奶油般光滑的利口酒",
    descEs: "Un licor cremoso y suave",
    descTh: "ลิเคียร์ที่ครีมมี่และนุ่ม",
    descVi: "Rượu liqueur kem mịn",
    priceKRW: 32000,
    image: "/baileys-liqueur.jpg",
  },
  {
    id: "cointreau",
    category: "liqueurs",
    nameKo: "꼬앙뜨로",
    nameEn: "Cointreau",
    nameJa: "コアントロー",
    nameZh: "君度",
    nameEs: "Cointreau",
    nameTh: "เคินโitoris",
    nameVi: "Cointreau",
    descKo: "오렌지 향의 우아한 리큐르",
    descEn: "An elegant orange-flavored liqueur",
    descJa: "オレンジ風味のエレガントなリキュール",
    descZh: "优雅的橙味利口酒",
    descEs: "Un licor elegante con sabor a naranja",
    descTh: "ลิเคียร์รสส้มที่หรูหรา",
    descVi: "Rượu liqueur cam thanh lịch",
    priceKRW: 28000,
    image: "/cointreau-liqueur.jpg",
  },
]

export function getMenuData(): MenuItemData[] {
  return menuData
}

export function getDefaultMenuItem(): MenuItemData {
  return menuData[0]
}
